### ISSUE TITLE
Lexer test-cases no longer work

### ISSUE THREAD

**Issue by Micaiah-Chang** [sphippen/uofu-compilers-tests#2]
I've spotted two bugs which stops proj1 ./test-cases from working.

One is that the libs previously put into the proj1/lib folder has been moved into the ./lib folder. However, the lib paths in the test-cases have not been fixed. This is a simple change.

The other is that the function "list-diff" is used in test-cases, but now does not seem to exist anywhere in the project, so throws an unbound identifier error. I'd fix it if I knew how to search through git history but I unfortunately do not.

**Comment by sphippen** [comment]
Unfortunately, we clobbered some of the proj1 stuff during the proj2 changes - list-diff got deleted.
Commit 877896bfaeb9d7b525c48e5 should bring it back (and fix the file path issues).
Does it work for you now?

**Comment by Micaiah-Chang** [comment]
They work now. Thanks! 

There's a separate issue regarding the test cases used for grading. I'll open up another issue for that.

**Comment by sphippen** [comment]
Awesome.
